apiVersion: v1
kind: Pod
metadata:
  name: podtest
  labels:
    app: front
    env: dev
spec:
  containers:
  - name:  cont1
    image:  nginx:alpine
---
apiVersion: v1
kind: Pod
metadata:
  name: podtest2
  labels:
    app: back
    env: dev
spec:
  containers:
  - name:  cont1
    image:  nginx:alpine